FROM mhart/alpine-node:12.21.0 as react-builder

WORKDIR /client

COPY package*.json /client/
COPY yarn.lock /client/

RUN yarn install
COPY . /client/

RUN GENERATE_SOURCEMAP=false yarn build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
#copy from build source to nginx
COPY --from=react-builder /client/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
